#!/usr/bin/env bash
# Build /etc/chromium-kiosk/config.yml from the knobs before the package's
# config watcher starts (every boot, idempotent) and on `bisquite-conf set`.
#
# The settings are the chromium-kiosk domain of bisquite-conf,
# /etc/bisquite/chromium-kiosk/config (schema: knobs next to this script).
# Up to 2.x the extension copied a YAML file of the package format verbatim,
# and write manifests edited it with `sed` — silently, when a key was missing.
# Keys of the package that are not knobs are constants below.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

log_info(){ echo -e "${GREEN}[INFO]${NC} $*" >&2; }
log_error(){ echo -e "${RED}[ERROR]${NC} $*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_CONFIG="${BISQUITE_CONF_ROOT:-}/etc/chromium-kiosk/config.yml"

# YAML single-quoted scalar: the only escape is '' for '.
yaml_str(){ local v="${1//\'/\'\'}"; printf "'%s'" "$v"; }

# Comma list -> YAML flow sequence of quoted strings.
yaml_list(){
  local out="" item
  local -a items=()
  [[ -n "$1" ]] && IFS=, read -r -a items <<< "$1"
  for item in "${items[@]}"; do out+="${out:+, }$(yaml_str "$item")"; done
  printf '[%s]' "$out"
}

main(){
  if [[ ! -f "$SCRIPT_DIR/lib/bisquite-conf" ]]; then
    log_error "lib/bisquite-conf not found at $SCRIPT_DIR/lib/bisquite-conf"
    exit 1
  fi
  # shellcheck source=/dev/null
  source "$SCRIPT_DIR/lib/bisquite-conf"
  conf_load chromium-kiosk || exit 1
  # Values go into YAML: a hand edit is checked before it lands there.
  conf_check chromium-kiosk || exit 1

  local rotation="$CHROMIUM_KIOSK_DISPLAY_ROTATION" tmp
  if [[ -z "$rotation" && -z "$CHROMIUM_KIOSK_SCREEN_ROTATION$CHROMIUM_KIOSK_TOUCHSCREEN_ROTATION" ]]; then
    rotation=normal
  fi

  install -d -m 0755 "$(dirname "$TARGET_CONFIG")"
  tmp="$(mktemp "$(dirname "$TARGET_CONFIG")/.config.yml.XXXXXX")"
  {
    echo "# Generated by configure-chromium-kiosk from /etc/bisquite/chromium-kiosk/config."
    echo "# Do not edit: rewritten on every boot. Change: bisquite-conf set chromium-kiosk KEY=VALUE"
    echo "WINDOW_MODE: $(yaml_str "$CHROMIUM_KIOSK_WINDOW_MODE")"
    echo "TOUCHSCREEN: $CHROMIUM_KIOSK_TOUCHSCREEN"
    echo "HOME_PAGE: $(yaml_str "$CHROMIUM_KIOSK_HOME_PAGE")"
    echo "IDLE_TIME: $CHROMIUM_KIOSK_IDLE_TIME"
    echo "WHITE_LIST:"
    echo "  ENABLED: $CHROMIUM_KIOSK_WHITE_LIST_ENABLED"
    echo "  URLS: $(yaml_list "$CHROMIUM_KIOSK_WHITE_LIST_URLS")"
    echo "  IFRAME_ENABLED: $CHROMIUM_KIOSK_WHITE_LIST_IFRAME_ENABLED"
    echo "NAV_BAR:"
    echo "  ENABLED: $CHROMIUM_KIOSK_NAV_BAR_ENABLED"
    echo "  ENABLED_BUTTONS: $(yaml_list "$CHROMIUM_KIOSK_NAV_BAR_BUTTONS")"
    echo "  HORIZONTAL_POSITION: 'center'"
    echo "  VERTICAL_POSITION: 'bottom'"
    echo "  WIDTH: 100"
    echo "  HEIGHT: 5"
    echo "  UNDERLAY: false"
    echo "VIRTUAL_KEYBOARD:"
    echo "  ENABLED: $CHROMIUM_KIOSK_VIRTUAL_KEYBOARD_ENABLED"
    [[ -n "$rotation" ]] && echo "DISPLAY_ROTATION: $(yaml_str "$rotation")"
    [[ -n "$CHROMIUM_KIOSK_SCREEN_ROTATION" ]] && echo "SCREEN_ROTATION: $(yaml_str "$CHROMIUM_KIOSK_SCREEN_ROTATION")"
    [[ -n "$CHROMIUM_KIOSK_TOUCHSCREEN_ROTATION" ]] && echo "TOUCHSCREEN_ROTATION: $(yaml_str "$CHROMIUM_KIOSK_TOUCHSCREEN_ROTATION")"
    echo "EXTRA_ARGUMENTS: $(yaml_str "$CHROMIUM_KIOSK_EXTRA_ARGUMENTS")"
    # An explicit empty list, never a bare key: `ALLOWED_FEATURES:` is YAML
    # null, i.e. "no value", not "nothing allowed".
    echo "ALLOWED_FEATURES: $(yaml_list "$CHROMIUM_KIOSK_ALLOWED_FEATURES")"
    echo "CURSOR:"
    echo "  ENABLED: $CHROMIUM_KIOSK_CURSOR_ENABLED"
  } > "$tmp"
  chmod 0644 "$tmp"
  mv -f "$tmp" "$TARGET_CONFIG"
  log_info "$TARGET_CONFIG собран: страница $CHROMIUM_KIOSK_HOME_PAGE, поворот ${rotation:-—}"
}

main "$@"
